# Setup
title:               Andres Villanueva for Language*
tagline:             'Everything is Language'
description:         'A repository for <a href="https://github.com/joseandresv/joseandresv.github.io.git" target="_blank">NLP/ML/CS projects</a>. 
Using a Lanyon Jekyll theme from <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:                 https://joseandresv.github.io/
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Andres Villanueva
  url:               https://www.linkedin.com/in/joseandresv/
  email:             joseavillanuevalopez@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: xxx-xxx-xxx
